-- Project Hermes MVP - seed data from the client's placeholder workbook
-- (Project_Hermes_MVP_Placeholder_Data_Model.xlsx).
-- Illustrative placeholder data only - not field verified.


INSERT INTO categories (category_id, category_name, description, sort_order) VALUES
    ('C001', 'Drinks', 'All beverages incl water,  beer, usually sold in litres or half litres', 1),
    ('C003', 'Food', 'Meals, snacks and sweets', 2),
    ('C004', 'Ride', 'Rides and amusement attractions', 3),
    ('C005', 'Game', 'Shooting galleries, lottery booths and skill games', 4),
    ('C006', 'Merchandise', 'Souvenirs and non-food items', 5);

INSERT INTO attributes (attribute_id, attribute_name, description, sort_order) VALUES
    ('A001', 'Alcoholic', 'Beer and other alcoholic beverages containing alcohol', 1),
    ('A002', 'Non-Alcoholic', 'Beverages without alcohol, such as water, lemonade, Spezi, juices and hot drinks', 2),
    ('A003', 'Vegan', 'Food and beverages made without any animal-derived ingredients', 3),
    ('A004', 'Non-Vegan', 'Food and beverages that contain or may contain animal-derived ingredients', 4);

INSERT INTO areas (area_id, area_name, description) VALUES
    ('A001', 'Oktoberfest', 'Main Oktoberfest area on Theresienwiese'),
    ('A002', 'Oide Wiesn', 'Historic/traditional Oktoberfest area');

INSERT INTO vendors (vendor_id, vendor_name, vendor_type, area_id, location, notes) VALUES
    ('V001', 'Augustiner-Festhalle', 'large_tent', 'A001', 'Wirtestrasse', 'Large beer tent example'),
    ('V002', 'Hacker-Festzelt', 'large_tent', 'A001', 'Wirtestrasse', 'Large beer tent example'),
    ('V003', 'Hofbraeu-Festzelt', 'large_tent', 'A001', 'Wirtestrasse', 'Large beer tent example'),
    ('V004', 'Schottenhamel-Festhalle', 'large_tent', 'A001', 'Wirtestrasse', 'Large beer tent example'),
    ('V005', 'Armbrustschuetzenzelt', 'large_tent', 'A001', 'Wirtestrasse', 'Large beer tent example'),
    ('V006', 'Loewenbraeu-Festzelt', 'large_tent', 'A001', 'Wirtestrasse', 'Large beer tent example'),
    ('V007', 'Kufflers Weinzelt', 'large_tent', 'A001', 'Wirtestrasse', 'Wine tent example'),
    ('V008', 'Ammer Entenbraterei', 'small_tent', 'A001', 'Street 2', 'Small tent / poultry example'),
    ('V009', 'Cafe Kaiserschmarrn', 'small_tent', 'A001', 'Street 3', 'Dessert/cafe tent example'),
    ('V010', 'Wirtshaus im Schichtl', 'small_tent', 'A001', 'Street 4', 'Small tent example'),
    ('V011', 'Museumszelt', 'oide_tent', 'A002', 'Oide Wiesn', 'Oide Wiesn tent example'),
    ('V012', 'Festzelt Tradition', 'oide_tent', 'A002', 'Oide Wiesn', 'Oide Wiesn tent example'),
    ('V013', 'Bratwurst Stand Mueller', 'food_stand', 'A001', 'Street 5', 'Food stand example'),
    ('V014', 'Steckerlfisch Huber', 'food_stand', 'A001', 'Street 6', 'Fish stand example'),
    ('V015', 'Brezn Baeckerei Seidl', 'food_stand', 'A001', 'Street 1', 'Bakery stand example'),
    ('V016', 'Pommes & Snacks Bauer', 'food_stand', 'A001', 'Street 7', 'Snack stand example'),
    ('V017', 'Mandelbrennerei Lenz', 'food_stand', 'A001', 'Street 8', 'Sweets stand example'),
    ('V018', 'Vegan Wiesn Kitchen', 'food_stand', 'A001', 'Street 9', 'Modern food stand example'),
    ('V019', 'Riesenrad Willenborg', 'ride', 'A001', 'Schaustellerstrasse', 'Ride example'),
    ('V020', 'Olympia Looping', 'ride', 'A001', 'Schaustellerstrasse', 'Ride example'),
    ('V021', 'Teufelsrad', 'ride', 'A001', 'Schaustellerstrasse', 'Ride example'),
    ('V022', 'Toboggan', 'ride', 'A001', 'Schaustellerstrasse', 'Ride example'),
    ('V023', 'Jules Verne Tower', 'ride', 'A001', 'Schaustellerstrasse', 'Ride example'),
    ('V024', 'Skater', 'ride', 'A001', 'Schaustellerstrasse', 'Ride example'),
    ('V025', 'Autoscooter Distel', 'ride', 'A001', 'Schaustellerstrasse', 'Ride example'),
    ('V026', 'Historic Chain Carousel', 'ride', 'A002', 'Oide Wiesn', 'Oide Wiesn ride example'),
    ('V027', 'Krinoline', 'ride', 'A002', 'Oide Wiesn', 'Oide Wiesn ride example'),
    ('V028', 'Schiessbude Wagner', 'game', 'A001', 'Street 10', 'Game stand example'),
    ('V029', 'Wurfspiel Schneider', 'game', 'A001', 'Street 11', 'Game stand example'),
    ('V030', 'Entenangeln Fischer', 'game', 'A001', 'Street 12', 'Game stand example'),
    ('V031', 'Hau den Lukas Bauer', 'game', 'A002', 'Oide Wiesn', 'Oide Wiesn game example'),
    ('V032', 'Losbude Glueckspilz', 'game', 'A001', 'Street 13', 'Lottery booth example'),
    ('V033', 'Lebkuchenherz Stand Rosi', 'merch_stand', 'A001', 'Street 14', 'Merchandise/sweets stand example'),
    ('V034', 'Souvenir Stand Bavaria', 'merch_stand', 'A001', 'Street 15', 'Souvenir stand example'),
    ('V035', 'Balloon Seller Munich', 'merch_stand', 'A001', 'Street 16', 'Merchandise stand example');

INSERT INTO products (product_id, category_id, product_name, variant, unit, is_traditional, attribute_id) VALUES
    ('P001', 'C001', 'Mass Helles', '1L', 'litre', TRUE, 'A001'),
    ('P002', 'C001', 'Mass Weissbier', '1L', 'litre', TRUE, 'A001'),
    ('P003', 'C001', 'Weissbier', '0.5L', 'litre', TRUE, 'A001'),
    ('P004', 'C001', 'Radler', '1L', 'litre', TRUE, 'A001'),
    ('P005', 'C001', 'Alcohol-Free Beer', '0.5L', 'litre', FALSE, 'A002'),
    ('P020', 'C001', 'Table Water', '1L', 'litre', FALSE, 'A002'),
    ('P021', 'C001', 'Mineral Water', '0.5L', 'litre', FALSE, 'A002'),
    ('P022', 'C001', 'Spezi', '1L', 'litre', FALSE, 'A002'),
    ('P023', 'C001', 'Lemonade', '1L', 'litre', FALSE, 'A002'),
    ('P024', 'C001', 'Apple Schorle', '0.5L', 'litre', FALSE, 'A002'),
    ('P025', 'C001', 'Coffee', 'Cup', 'cup', FALSE, 'A002'),
    ('P026', 'C001', 'Hot Chocolate', 'Cup', 'cup', FALSE, 'A002'),
    ('P040', 'C003', 'Half Chicken', 'Standard', 'piece', TRUE, NULL),
    ('P041', 'C003', 'Bio Half Chicken', 'With potato salad', 'piece', FALSE, NULL),
    ('P042', 'C003', 'Pork Knuckle', 'Standard', 'portion', TRUE, NULL),
    ('P043', 'C003', 'Weisswurst', 'Pair', 'portion', TRUE, NULL),
    ('P044', 'C003', 'Brezn', 'Large', 'piece', TRUE, NULL),
    ('P045', 'C003', 'Kaiserschmarrn', 'Standard', 'portion', TRUE, NULL),
    ('P046', 'C003', 'Bratwurst in Semmel', 'Standard', 'piece', TRUE, NULL),
    ('P047', 'C003', 'Steckerlfisch', 'Mackerel', 'piece', TRUE, NULL),
    ('P048', 'C003', 'Fischsemmel', 'Herring', 'piece', TRUE, NULL),
    ('P049', 'C003', 'Pommes', 'Regular', 'portion', FALSE, NULL),
    ('P050', 'C003', 'Cheese Spaetzle', 'Standard', 'portion', TRUE, NULL),
    ('P051', 'C003', 'Vegan Sausage in Semmel', 'Standard', 'piece', FALSE, NULL),
    ('P052', 'C003', 'Roasted Almonds', '100g', 'bag', TRUE, NULL),
    ('P053', 'C003', 'Chocolate Fruit Skewer', 'Standard', 'piece', TRUE, NULL),
    ('P080', 'C004', 'Ferris Wheel Ride', 'Single Ride', 'ticket', TRUE, NULL),
    ('P081', 'C004', 'Roller Coaster Ride', 'Single Ride', 'ticket', FALSE, NULL),
    ('P082', 'C004', 'Devil''s Wheel Entry', 'Single Entry', 'ticket', TRUE, NULL),
    ('P083', 'C004', 'Toboggan Entry', 'Single Entry', 'ticket', TRUE, NULL),
    ('P084', 'C004', 'Tower Swing Ride', 'Single Ride', 'ticket', FALSE, NULL),
    ('P085', 'C004', 'Top Scan Ride', 'Single Ride', 'ticket', FALSE, NULL),
    ('P086', 'C004', 'Bumper Car Ride', 'Single Ride', 'ticket', FALSE, NULL),
    ('P087', 'C004', 'Historic Chain Carousel', 'Single Ride', 'ticket', TRUE, NULL),
    ('P088', 'C004', 'Krinoline Ride', 'Single Ride', 'ticket', TRUE, NULL),
    ('P089', 'C004', 'Children''s Carousel', 'Single Ride', 'ticket', TRUE, NULL),
    ('P100', 'C005', 'Shooting Gallery', '1 Shot', 'shot', TRUE, NULL),
    ('P101', 'C005', 'Shooting Gallery', '10 Shots', 'shots', TRUE, NULL),
    ('P102', 'C005', 'Shooting Gallery', '20 Shots', 'shots', TRUE, NULL),
    ('P103', 'C005', 'Ring Toss', '5 Rings', 'round', TRUE, NULL),
    ('P104', 'C005', 'Duck Fishing', '1 Round', 'round', TRUE, NULL),
    ('P105', 'C005', 'Strongman Hammer', '1 Try', 'try', TRUE, NULL),
    ('P106', 'C005', 'Lottery Ticket', '1 Ticket', 'ticket', TRUE, NULL),
    ('P107', 'C005', 'Can Knockdown', '3 Balls', 'round', TRUE, NULL),
    ('P120', 'C006', 'Gingerbread Heart', 'Medium', 'piece', TRUE, NULL),
    ('P121', 'C006', 'Gingerbread Heart', 'Large', 'piece', TRUE, NULL),
    ('P122', 'C006', 'Oktoberfest Mug', 'Souvenir', 'piece', FALSE, NULL),
    ('P123', 'C006', 'Felt Hat', 'Souvenir', 'piece', FALSE, NULL),
    ('P124', 'C006', 'Balloon', 'Standard', 'piece', FALSE, NULL),
    ('P125', 'C006', 'Souvenir Pin', 'Standard', 'piece', FALSE, NULL);
